name: Github CI

on:
  push:
    branches:
      - main
      - v8.16
  pull_request:
    branches:
      - main
      - v8.16

jobs:
  build:
    strategy:
      matrix:
        ocaml: [4.14.x]
        os: [macOS-latest, ubuntu-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: 🔭 Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: 🐫 Setup OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml }}
          dune-cache: true

      - name: 🐫🐪🐫 Get dependencies
        run: opam exec -- make opam-deps

      - name: 🧱 Build coq-lsp
        run: opam exec -- make build

  client-compile:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./editor/code
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm run compile

  lint-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: 🔭 Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: 🐫 Setup OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.14.x
          dune-cache: true

      # TODO make this faster, use nix?

      - name: 🐫🐪🐫 Get dependencies
        run: |
          opam exec -- make opam-deps
          opam exec -- make opam-dev-deps

      - name: 📐 Format
        run: opam exec -- make fmt
